image:
  name: python-tools

before_script:
  - apt-get update
  - apt-get install -qy python3 python3-pip
  - python3 --version
  - pip3 install poetry
  - poetry config virtualenvs.create false
  - poetry install --no-root

stages:
  - Static Analysis
  - Testing

flake8:
  stage: Static Analysis
  only:
    - merge_requests
  allow_failure: true
  script:
    - poetry run flake8 .

pylint:
  stage: Static Analysis
  only:
    - merge_requests
  allow_failure: true
  script:
    - poetry run pylint main.py core/ test/

mypy:
  stage: Static Analysis
  only:
    - merge_requests
  allow_failure: true
  script:
    - poetry run mypy . --check-untyped-defs


pytest:
  stage: Testing
  only:
    - merge_requests
  allow_failure: true
  script:
    - poetry run pytest test/