image:
  name: python-tools

before_script:
  - apt-get update
  - apt-get install -qy python3 python3-pip
  - python3 --version
  - pip3 install poetry
  - poetry install
  - source `poetry env info --path /bin/activate`

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  only:
    - master
    - merge_requests
  allow_failure: true
  script:
    - flake8 .

pylint:
  stage: Static Analysis
  only:
    - master
    - merge_requests
  allow_failure: true
  script:
    - find . -type f -name "*.py" | xargs pylint
