image:
  name: python-tools

before_script:
  - apt-get update
  - apt-get install -qy python3 python3-pip
  - python3 --version
  - pip3 install poetry
  - export PATH=$PATH:/root/.local/bin
  - poetry config virtualenvs.in-project true
  - poetry env use python3
  - poetry install --no-root

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key:
    files:
      - poetry.lock
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .venv
    - .cache/pip

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  only:
    - master
    - merge_requests
  allow_failure: true
  script:
    - poetry run flake8 .

mypy:
  stage: Static Analysis
  only:
    - master
    - merge_requests
  allow_failure: true
  script:
    - poetry run mypy .
