Executing examples/program.asm.o...
Program(data=DataSection(data={'A': Number(value=4660),
                               'B': Number(value=17185),
                               'C': Number(value=0),
                               'D': String(value='Hello World')}),
        text=TextSection(labels={'.exit': 10, '.inc_rax': 7},
                         lines=[Instruction(name='XOR',
                                            info=InstructionInfo(operand_types={(core.model.Address | core.model.Register,
                                                                                 core.model.Address | core.model.Register | core.model.Constant)},
                                                                 operand_values=[Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0))])),
                                Instruction(name='MOV',
                                            info=InstructionInfo(operand_types={(core.model.Register | core.model.Address,
                                                                                 core.model.Register | core.model.Address | core.model.Constant)},
                                                                 operand_values=[Register(name='RDX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Number(value=0)])),
                                Instruction(name='LD',
                                            info=InstructionInfo(operand_types={(<class 'core.model.Register'>,
                                                                                 <class 'core.model.Address'>)},
                                                                 operand_values=[Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Address(value=0),
                                                                                 Register(name='RDX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Address(value=0)])),
                                Instruction(name='LD',
                                            info=InstructionInfo(operand_types={(<class 'core.model.Register'>,
                                                                                 <class 'core.model.Address'>)},
                                                                 operand_values=[Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Address(value=0),
                                                                                 Register(name='RDX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Address(value=0)])),
                                Instruction(name='ADD',
                                            info=InstructionInfo(operand_types={(core.model.Address | core.model.Register,
                                                                                 core.model.Address | core.model.Register | core.model.Number),
                                                                                (core.model.Address | core.model.Register,
                                                                                 core.model.Address | core.model.Register | core.model.Number,
                                                                                 core.model.Address | core.model.Register | core.model.Number)},
                                                                 operand_values=[Address(value=0),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RDX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0))])),
                                Instruction(name='JMP',
                                            info=InstructionInfo(operand_types={(<class 'core.model.Label'>,)},
                                                                 operand_values=[Label(name='.inc_rax'),
                                                                                 Label(name='.exit')])),
                                Instruction(name='XOR',
                                            info=InstructionInfo(operand_types={(core.model.Address | core.model.Register,
                                                                                 core.model.Address | core.model.Register | core.model.Constant)},
                                                                 operand_values=[Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0)),
                                                                                 Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0))])),
                                Instruction(name='INC',
                                            info=InstructionInfo(operand_types={(core.model.Address | core.model.Register,)},
                                                                 operand_values=[Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0))])),
                                Instruction(name='JMP',
                                            info=InstructionInfo(operand_types={(<class 'core.model.Label'>,)},
                                                                 operand_values=[Label(name='.inc_rax'),
                                                                                 Label(name='.exit')])),
                                Instruction(name='DEC',
                                            info=InstructionInfo(operand_types={(core.model.Address | core.model.Register,)},
                                                                 operand_values=[Register(name='RAX',
                                                                                          info=RegisterInfo(can_read=True,
                                                                                                            can_write=True,
                                                                                                            size=4,
                                                                                                            value=0))])),
                                Instruction(name='HLT',
                                            info=InstructionInfo(operand_types=set(),
                                                                 operand_values=[]))]))
